### ISSUE TITLE
android/example 构建成功后运行时异常 java.lang.UnsatisfiedLinkError: Native method not found: com.artifex.mupdf.fitz.Context.initNative:()I

### ISSUE THREAD

**Issue by scientist2009** [ZhangSir/mupdf-source#1]
构建环境如下：
OS : Windows 10 64位系统 和 Kali2 Linux 64位系统（主要是在Win10测试的，但是Linux下也存在同样的问题）
NDK: android-ndk32-r10b-x86_64
构建的过程，完全参考官方提供的《How To ...》 来做的。
android/viewer 下的例子已经能够成功运行，不报错。
按照android/example/README 要求，将viewer/libs/armeabi/libmupdf_java.so 复制到指定的路径下，用gradle2.10来构建example。
在手机运行example，选择一个pdf文件打开时，崩溃了：

> 08-30 08:37:52.157: W/dalvikvm(24297): No implementation found for native 
> Lcom/artifex/mupdf/fitz/Context;.initNative:()I
> 08-30 08:37:52.157: W/dalvikvm(24297): Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/artifex/mupdf/fitz/Context;

请问android/example怎样构建才能成功呢？我已经查了很多英文资料了，都没有找到解决方法。

**完整的Log如下：**
08-30 08:37:51.836: I/BackTouch_ViewRoot(24297): disableBackTouch:false
08-30 08:37:52.096: D/dalvikvm(24297): Trying to load lib /mnt/asec/com.artifex.mupdf.example-1/lib/libmupdf_java.so 0x4249cc08
08-30 08:37:52.157: D/dalvikvm(24297): Added shared lib /mnt/asec/com.artifex.mupdf.example-1/lib/libmupdf_java.so 0x4249cc08
08-30 08:37:52.157: D/dalvikvm(24297): No JNI_OnLoad found in /mnt/asec/com.artifex.mupdf.example-1/lib/libmupdf_java.so 0x4249cc08, skipping init
08-30 08:37:52.157: W/dalvikvm(24297): No implementation found for native Lcom/artifex/mupdf/fitz/Context;.initNative:()I
08-30 08:37:52.157: W/dalvikvm(24297): Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/artifex/mupdf/fitz/Context;
08-30 08:37:52.157: W/dalvikvm(24297): Exception Ljava/lang/ExceptionInInitializerError; thrown while initializing Lcom/artifex/mupdf/fitz/Document;
08-30 08:37:52.167: D/AndroidRuntime(24297): Shutting down VM
08-30 08:37:52.167: W/dalvikvm(24297): threadid=1: thread exiting with uncaught exception (group=0x4120cac8)
08-30 08:37:52.177: E/AndroidRuntime(24297): FATAL EXCEPTION: main
08-30 08:37:52.177: E/AndroidRuntime(24297): java.lang.ExceptionInInitializerError
08-30 08:37:52.177: E/AndroidRuntime(24297):    at com.artifex.mupdf.example.DocViewActivity.onCreate(DocViewActivity.java:41)
08-30 08:37:52.177: E/AndroidRuntime(24297):    at android.app.Activity.performCreate(Activity.java:5173)
08-30 08:37:52.177: E/AndroidRuntime(24297):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1083)
08-30 08:37:52.177: E/AndroidRuntime(24297):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
08-30 08:37:52.177: E/AndroidRuntime(24297):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2262)
08-30 08:37:52.177: E/AndroidRuntime(24297):    at android.app.ActivityThread.access$600(ActivityThread.java:148)
08-30 08:37:52.177: E/AndroidRuntime(24297):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
08-30 08:37:52.177: E/AndroidRuntime(24297):    at android.os.Handler.dispatchMessage(Handler.java:99)
08-30 08:37:52.177: E/AndroidRuntime(24297):    at android.os.Looper.loop(Looper.java:137)
08-30 08:37:52.177: E/AndroidRuntime(24297):    at android.app.ActivityThread.main(ActivityThread.java:5145)
08-30 08:37:52.177: E/AndroidRuntime(24297):    at java.lang.reflect.Method.invokeNative(Native Method)
08-30 08:37:52.177: E/AndroidRuntime(24297):    at java.lang.reflect.Method.invoke(Method.java:511)
08-30 08:37:52.177: E/AndroidRuntime(24297):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
08-30 08:37:52.177: E/AndroidRuntime(24297):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:591)
08-30 08:37:52.177: E/AndroidRuntime(24297):    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
08-30 08:37:52.177: E/AndroidRuntime(24297):    at dalvik.system.NativeStart.main(Native Method)
08-30 08:37:52.177: E/AndroidRuntime(24297): Caused by: java.lang.ExceptionInInitializerError
08-30 08:37:52.177: E/AndroidRuntime(24297):    at com.artifex.mupdf.fitz.Document.<clinit>(Document.java:6)
08-30 08:37:52.177: E/AndroidRuntime(24297):    ... 16 more
08-30 08:37:52.177: E/AndroidRuntime(24297): Caused by: java.lang.UnsatisfiedLinkError: Native method not found: com.artifex.mupdf.fitz.Context.initNative:()I
08-30 08:37:52.177: E/AndroidRuntime(24297):    at com.artifex.mupdf.fitz.Context.initNative(Native Method)
08-30 08:37:52.177: E/AndroidRuntime(24297):    at com.artifex.mupdf.fitz.Context.init(Context.java:18)
08-30 08:37:52.177: E/AndroidRuntime(24297):    at com.artifex.mupdf.fitz.Context.<clinit>(Context.java:23)
08-30 08:37:52.177: E/AndroidRuntime(24297):    ... 17 more

**Comment by ZhangSir** [comment]
08-30 08:37:52.177: E/AndroidRuntime(24297): Caused by: java.lang.ExceptionInInitializerError
08-30 08:37:52.177: E/AndroidRuntime(24297): at com.artifex.mupdf.fitz.Document.(Document.java:6)
08-30 08:37:52.177: E/AndroidRuntime(24297): ... 16 more
08-30 08:37:52.177: E/AndroidRuntime(24297): Caused by: java.lang.UnsatisfiedLinkError: Native method not found: com.artifex.mupdf.fitz.Context.initNative:()I
08-30 08:37:52.177: E/AndroidRuntime(24297): at com.artifex.mupdf.fitz.Context.initNative(Native Method)

看LOG应该是SO库里声明的方法找不到，你检查一下你这项目中声明加载SO库中的方法的java文件的包名，最好对比一下android/viewer 下的例子，要确保包名相同才能找到so库中的方法；

**Comment by scientist2009** [comment]
额，我在StackOverflow看到别人也是这么说的，按照他们给出的解决方案，在mupdf.c里改掉了那个包名后发现一个问题，感觉貌似是官方已经不再维护example了，阅读了一下相关的JNI代码，发现viewer和example的实现完全不一样，example根本没有参照viewer的JNI调用libmupdf_java.so的API，感觉example用的是一套早期的API，貌似直接用viewer去改成自己需要的阅读器会比较好。个人感觉是这样。
